# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tarzan <elakhfif@student.1337.ma>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/27 23:28:09 by tarzan            #+#    #+#              #
#    Updated: 2024/10/25 21:33:57 by elakhfif         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: inception

services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        volumes:
            - database:/data
        networks:
            inception_network:
                aliases:
                    - database
                    - mariadb
        secrets:
            - database-credentials
        healthcheck:
            test: ["CMD", "mysqladmin", "-u", "stats", "--protocol=tcp", "ping"]
            interval: 5m
            timeout: 5s
            retries: 3
            start_period: 2m
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
        env_file:
            - path: ./.env
              required: true
        volumes:
            - wordprss_files:/www
        networks:
            inception_network:
                aliases:
                    - wordpress
        secrets:
            - database-credentials
            - wordpress-credentials
        depends_on:
            mariadb:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "pgrep", "php-fpm"]
            interval: 5m
            timeout: 5s
            retries: 3
            start_period: 2m
        restart: always
    
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
        ports:
            - 443:443
        volumes:
            - wordprss_files:/www
        networks:
            inception_network:
        depends_on:
            wordpress:
                condition: service_healthy
        restart: always

    ftpserv:
        container_name: vsftpd
        build: ./requirements/bonus/vsftpd
        ports:
            - 21:21/tcp
            - 5000-5050:5000-5050/tcp
        networks:
            inception_network:
        depends_on:
            wordpress:
                condition: service_healthy

        volumes:
            - wordprss_files:/www
        secrets:
            - ftp-credentials
        restart: always

    redis:
        container_name: redis
        build: ./requirements/bonus/redis
        networks:
            inception_network:
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5m
            timeout: 5s
            retries: 3
            start_period: 2m
        restart: always

volumes:
    database:
      driver: local
      driver_opts:
        type: none
        device: /home/elakhfif/data/database
        o: bind
    wordprss_files:
      driver: local
      driver_opts:
        type: none
        device: /home/elakhfif/data/wordprss_files
        o: bind

networks:
    inception_network:

secrets:
    database-credentials:
        file: ../secrets/db_credentials.env
    wordpress-credentials:
        file: ../secrets/wp_credentials.env
    ftp-credentials:
        file: ../secrets/ftp_credentials.env
