# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: elakhfif <elakhfif@student.1337.ma>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 09:25:07 by elakhfif          #+#    #+#              #
#    Updated: 2024/02/20 21:45:15 by elakhfif         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# docker-compose.yml
