# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tarzan <elakhfif@student.1337.ma>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/27 23:28:09 by tarzan            #+#    #+#              #
#    Updated: 2024/09/27 23:37:42 by tarzan           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.8'
services:

  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./srcs/requirements/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - inception_network
    restart: always

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception_network:
    driver: bridge
